"""SQLAlchemy declarative base shared by all ORM models.

The explicit naming convention makes constraint/index names deterministic,
which keeps Alembic autogenerated migrations stable across environments —
without it, dropping an unnamed constraint later becomes guesswork.
"""

from enum import Enum as PyEnum

from sqlalchemy import Enum as SAEnum
from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase

NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)


def str_enum(enum_cls: type[PyEnum], length: int) -> SAEnum:
    """A VARCHAR-backed column for a `str, Enum` class, matched on `.value`.

    SQLAlchemy's `Enum` type defaults to storing/matching a Python enum's
    *member name* ("MEDIUM"), not its `.value` ("Medium") — but `.value` is
    what every schema and service in this codebase treats as the canonical
    string. Without `values_callable`, writes succeed but reads raise
    `LookupError` the moment a row is read back (found live, first surfaced
    by app/models/risk.py — see that module's git history). `native_enum=False`
    (plain VARCHAR, not `CREATE TYPE ... AS ENUM`) so adding a new value
    later is a normal migration, not an `ALTER TYPE ADD VALUE`.
    """
    return SAEnum(enum_cls, native_enum=False, length=length, values_callable=lambda cls: [e.value for e in cls])
