"""add compliance documents chat sessions and messages

Revision ID: 900e3391549b
Revises: 810b77bb5b78
Create Date: 2026-07-22 08:07:48.308314
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '900e3391549b'
down_revision: str | None = '810b77bb5b78'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_chat_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_compliance_chat_sessions_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_compliance_chat_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_chat_sessions'))
    )
    op.create_index(op.f('ix_compliance_chat_sessions_organization_id'), 'compliance_chat_sessions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_compliance_chat_sessions_user_id'), 'compliance_chat_sessions', ['user_id'], unique=False)
    op.create_table('compliance_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'ready', 'failed', name='documentstatus', native_enum=False, length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_compliance_documents_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_compliance_documents_uploaded_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_documents'))
    )
    op.create_index(op.f('ix_compliance_documents_organization_id'), 'compliance_documents', ['organization_id'], unique=False)
    op.create_table('compliance_chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', name='chatrole', native_enum=False, length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=50), nullable=True),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_compliance_chat_messages_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['compliance_chat_sessions.id'], name=op.f('fk_compliance_chat_messages_session_id_compliance_chat_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_chat_messages'))
    )
    op.create_index(op.f('ix_compliance_chat_messages_organization_id'), 'compliance_chat_messages', ['organization_id'], unique=False)
    op.create_index('ix_compliance_chat_messages_session_created_at', 'compliance_chat_messages', ['session_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_compliance_chat_messages_session_created_at', table_name='compliance_chat_messages')
    op.drop_index(op.f('ix_compliance_chat_messages_organization_id'), table_name='compliance_chat_messages')
    op.drop_table('compliance_chat_messages')
    op.drop_index(op.f('ix_compliance_documents_organization_id'), table_name='compliance_documents')
    op.drop_table('compliance_documents')
    op.drop_index(op.f('ix_compliance_chat_sessions_user_id'), table_name='compliance_chat_sessions')
    op.drop_index(op.f('ix_compliance_chat_sessions_organization_id'), table_name='compliance_chat_sessions')
    op.drop_table('compliance_chat_sessions')
    # ### end Alembic commands ###
