"""add facility hierarchy (factories, sites, buildings, zones)

Revision ID: 99f0a9b23be2
Revises: d1e29503faf3
Create Date: 2026-07-21 23:37:33.242464
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '99f0a9b23be2'
down_revision: str | None = 'd1e29503faf3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_factories_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_factories')),
    sa.UniqueConstraint('organization_id', 'code', name='uq_factories_org_code')
    )
    op.create_index(op.f('ix_factories_organization_id'), 'factories', ['organization_id'], unique=False)
    op.create_table('sites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('factory_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], name=op.f('fk_sites_factory_id_factories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_sites_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sites')),
    sa.UniqueConstraint('factory_id', 'code', name='uq_sites_factory_code')
    )
    op.create_index(op.f('ix_sites_factory_id'), 'sites', ['factory_id'], unique=False)
    op.create_index(op.f('ix_sites_organization_id'), 'sites', ['organization_id'], unique=False)
    op.create_table('buildings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('floor_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_buildings_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_buildings_site_id_sites'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_buildings')),
    sa.UniqueConstraint('site_id', 'code', name='uq_buildings_site_code')
    )
    op.create_index(op.f('ix_buildings_organization_id'), 'buildings', ['organization_id'], unique=False)
    op.create_index(op.f('ix_buildings_site_id'), 'buildings', ['site_id'], unique=False)
    op.create_table('zones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('building_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('zone_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], name=op.f('fk_zones_building_id_buildings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_zones_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_zones')),
    sa.UniqueConstraint('building_id', 'code', name='uq_zones_building_code')
    )
    op.create_index(op.f('ix_zones_building_id'), 'zones', ['building_id'], unique=False)
    op.create_index(op.f('ix_zones_organization_id'), 'zones', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zones_organization_id'), table_name='zones')
    op.drop_index(op.f('ix_zones_building_id'), table_name='zones')
    op.drop_table('zones')
    op.drop_index(op.f('ix_buildings_site_id'), table_name='buildings')
    op.drop_index(op.f('ix_buildings_organization_id'), table_name='buildings')
    op.drop_table('buildings')
    op.drop_index(op.f('ix_sites_organization_id'), table_name='sites')
    op.drop_index(op.f('ix_sites_factory_id'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_factories_organization_id'), table_name='factories')
    op.drop_table('factories')
    # ### end Alembic commands ###
