"""add emergency protocols

Revision ID: 5c19f87c74bd
Revises: a824c497a505
Create Date: 2026-07-22 09:45:52.537685
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '5c19f87c74bd'
down_revision: str | None = 'a824c497a505'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emergency_protocols',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hazard_type', sa.String(length=50), nullable=False),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evacuation_route', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_emergency_protocols_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emergency_protocols'))
    )
    op.create_index(op.f('ix_emergency_protocols_hazard_type'), 'emergency_protocols', ['hazard_type'], unique=False)
    op.create_index(op.f('ix_emergency_protocols_organization_id'), 'emergency_protocols', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emergency_protocols_organization_id'), table_name='emergency_protocols')
    op.drop_index(op.f('ix_emergency_protocols_hazard_type'), table_name='emergency_protocols')
    op.drop_table('emergency_protocols')
    # ### end Alembic commands ###
