"""add sensors permits maintenance and shifts

Revision ID: 6168573dc611
Revises: 2d8e37504eff
Create Date: 2026-07-22 09:26:02.846552
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '6168573dc611'
down_revision: str | None = '2d8e37504eff'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shifts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('factory_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], name=op.f('fk_shifts_factory_id_factories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_shifts_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shifts'))
    )
    op.create_index(op.f('ix_shifts_factory_id'), 'shifts', ['factory_id'], unique=False)
    op.create_index(op.f('ix_shifts_organization_id'), 'shifts', ['organization_id'], unique=False)
    op.create_table('shift_changeover_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('factory_id', sa.UUID(), nullable=False),
    sa.Column('shift_id', sa.UUID(), nullable=False),
    sa.Column('changeover_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], name=op.f('fk_shift_changeover_events_factory_id_factories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_shift_changeover_events_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name=op.f('fk_shift_changeover_events_shift_id_shifts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shift_changeover_events'))
    )
    op.create_index(op.f('ix_shift_changeover_events_changeover_at'), 'shift_changeover_events', ['changeover_at'], unique=False)
    op.create_index(op.f('ix_shift_changeover_events_factory_id'), 'shift_changeover_events', ['factory_id'], unique=False)
    op.create_index(op.f('ix_shift_changeover_events_organization_id'), 'shift_changeover_events', ['organization_id'], unique=False)
    op.create_table('equipment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('equipment_type', sa.String(length=100), nullable=False),
    sa.Column('criticality', sa.Enum('Low', 'Medium', 'High', 'Critical', name='equipmentcriticality', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_equipment_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_equipment_zone_id_zones'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipment'))
    )
    op.create_index(op.f('ix_equipment_organization_id'), 'equipment', ['organization_id'], unique=False)
    op.create_index(op.f('ix_equipment_zone_id'), 'equipment', ['zone_id'], unique=False)
    op.create_table('sensor_devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('sensor_type', sa.Enum('gas', 'temperature', 'pressure', 'vibration', name='sensortype', native_enum=False, length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('baseline_min', sa.Float(), nullable=False),
    sa.Column('baseline_max', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_sensor_devices_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_sensor_devices_zone_id_zones'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sensor_devices'))
    )
    op.create_index(op.f('ix_sensor_devices_organization_id'), 'sensor_devices', ['organization_id'], unique=False)
    op.create_index(op.f('ix_sensor_devices_zone_id'), 'sensor_devices', ['zone_id'], unique=False)
    op.create_table('work_permits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('permit_type', sa.Enum('hot_work', 'confined_space', 'electrical', 'working_at_height', 'general', name='permittype', native_enum=False, length=30), nullable=False),
    sa.Column('status', sa.Enum('requested', 'approved', 'active', 'closed', 'revoked', name='permitstatus', native_enum=False, length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('issued_by', sa.UUID(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['issued_by'], ['users.id'], name=op.f('fk_work_permits_issued_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_work_permits_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_work_permits_zone_id_zones'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_permits'))
    )
    op.create_index(op.f('ix_work_permits_organization_id'), 'work_permits', ['organization_id'], unique=False)
    op.create_index(op.f('ix_work_permits_zone_id'), 'work_permits', ['zone_id'], unique=False)
    op.create_table('maintenance_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'in_progress', 'completed', name='maintenancestatus', native_enum=False, length=20), nullable=False),
    sa.Column('technician', sa.String(length=200), nullable=True),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_maintenance_records_equipment_id_equipment'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_maintenance_records_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maintenance_records'))
    )
    op.create_index(op.f('ix_maintenance_records_equipment_id'), 'maintenance_records', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_maintenance_records_organization_id'), 'maintenance_records', ['organization_id'], unique=False)
    op.create_table('sensor_readings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sensor_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_sensor_readings_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor_devices.id'], name=op.f('fk_sensor_readings_sensor_id_sensor_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sensor_readings'))
    )
    op.create_index(op.f('ix_sensor_readings_organization_id'), 'sensor_readings', ['organization_id'], unique=False)
    op.create_index(op.f('ix_sensor_readings_recorded_at'), 'sensor_readings', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_sensor_readings_sensor_id'), 'sensor_readings', ['sensor_id'], unique=False)
    op.create_index('ix_sensor_readings_sensor_recorded_at', 'sensor_readings', ['sensor_id', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sensor_readings_sensor_recorded_at', table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_sensor_id'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_recorded_at'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_organization_id'), table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_index(op.f('ix_maintenance_records_organization_id'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_equipment_id'), table_name='maintenance_records')
    op.drop_table('maintenance_records')
    op.drop_index(op.f('ix_work_permits_zone_id'), table_name='work_permits')
    op.drop_index(op.f('ix_work_permits_organization_id'), table_name='work_permits')
    op.drop_table('work_permits')
    op.drop_index(op.f('ix_sensor_devices_zone_id'), table_name='sensor_devices')
    op.drop_index(op.f('ix_sensor_devices_organization_id'), table_name='sensor_devices')
    op.drop_table('sensor_devices')
    op.drop_index(op.f('ix_equipment_zone_id'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_organization_id'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_index(op.f('ix_shift_changeover_events_organization_id'), table_name='shift_changeover_events')
    op.drop_index(op.f('ix_shift_changeover_events_factory_id'), table_name='shift_changeover_events')
    op.drop_index(op.f('ix_shift_changeover_events_changeover_at'), table_name='shift_changeover_events')
    op.drop_table('shift_changeover_events')
    op.drop_index(op.f('ix_shifts_organization_id'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_factory_id'), table_name='shifts')
    op.drop_table('shifts')
    # ### end Alembic commands ###
