"""seed rbac (roles, permissions, default org, bootstrap admin)

Revision ID: d1e29503faf3
Revises: 7d25e3d52d9d
Create Date: 2026-07-21 23:08:29.989305

Deliberately hand-written, not autogenerated: this is data, not schema.
Uses `sa.table()` proxies rather than importing the ORM models directly —
the standard Alembic practice for data migrations, so a future change to
`app/models/*.py` can never silently alter what this specific, already-run
migration does.

Reads bootstrap-admin credentials from Settings (SENTINEL_ADMIN_EMAIL /
SENTINEL_ADMIN_PASSWORD) the same way alembic/env.py already reads the
database URL from Settings — if unset, admin creation is skipped, but
roles/permissions are still seeded.
"""

import uuid
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.core.config import get_settings
from app.core.permissions import ALL_PERMISSIONS, DEFAULT_ROLE_PERMISSIONS, SYSTEM_ROLES
from app.core.permissions import ADMIN as ADMIN_ROLE_NAME
from app.core.security import hash_password

revision: str = "d1e29503faf3"
down_revision: str | None = "7d25e3d52d9d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

organizations_table = sa.table(
    "organizations",
    sa.column("id", sa.UUID()),
    sa.column("name", sa.String()),
    sa.column("slug", sa.String()),
)
permissions_table = sa.table(
    "permissions",
    sa.column("id", sa.UUID()),
    sa.column("code", sa.String()),
    sa.column("description", sa.String()),
)
roles_table = sa.table(
    "roles",
    sa.column("id", sa.UUID()),
    sa.column("name", sa.String()),
    sa.column("description", sa.String()),
)
role_permissions_table = sa.table(
    "role_permissions",
    sa.column("role_id", sa.UUID()),
    sa.column("permission_id", sa.UUID()),
)
users_table = sa.table(
    "users",
    sa.column("id", sa.UUID()),
    sa.column("organization_id", sa.UUID()),
    sa.column("email", sa.String()),
    sa.column("hashed_password", sa.String()),
    sa.column("full_name", sa.String()),
    sa.column("is_active", sa.Boolean()),
)
user_roles_table = sa.table(
    "user_roles",
    sa.column("user_id", sa.UUID()),
    sa.column("role_id", sa.UUID()),
)


def upgrade() -> None:
    settings = get_settings()

    org_id = uuid.uuid4()
    op.bulk_insert(
        organizations_table,
        [{"id": org_id, "name": settings.default_organization_name, "slug": settings.default_organization_slug}],
    )

    permission_ids: dict[str, uuid.UUID] = {code: uuid.uuid4() for code in ALL_PERMISSIONS}
    op.bulk_insert(
        permissions_table,
        [
            {"id": permission_ids[code], "code": code, "description": description}
            for code, description in ALL_PERMISSIONS.items()
        ],
    )

    role_ids: dict[str, uuid.UUID] = {name: uuid.uuid4() for name in SYSTEM_ROLES}
    op.bulk_insert(
        roles_table,
        [{"id": role_ids[name], "name": name, "description": f"System role: {name}"} for name in SYSTEM_ROLES],
    )

    op.bulk_insert(
        role_permissions_table,
        [
            {"role_id": role_ids[role_name], "permission_id": permission_ids[code]}
            for role_name, codes in DEFAULT_ROLE_PERMISSIONS.items()
            for code in codes
        ],
    )

    if settings.admin_email and settings.admin_password:
        admin_id = uuid.uuid4()
        op.bulk_insert(
            users_table,
            [
                {
                    "id": admin_id,
                    "organization_id": org_id,
                    "email": settings.admin_email.lower(),
                    "hashed_password": hash_password(settings.admin_password.get_secret_value()),
                    "full_name": "SentinelAI Admin",
                    "is_active": True,
                }
            ],
        )
        op.bulk_insert(user_roles_table, [{"user_id": admin_id, "role_id": role_ids[ADMIN_ROLE_NAME]}])
    else:
        print(
            "WARNING: SENTINEL_ADMIN_EMAIL / SENTINEL_ADMIN_PASSWORD not set — "
            "skipped bootstrap admin creation. Roles and permissions were "
            "still seeded; create the first user directly in the database, "
            "or set these env vars and re-run after a downgrade."
        )


def downgrade() -> None:
    settings = get_settings()

    # Scoped to exactly what upgrade() could have created. role_permissions/
    # roles/permissions are blanket-deleted because nothing else can own
    # rows in those tables at this point in the migration history — this is
    # the first migration that ever populates them.
    op.execute(sa.text("DELETE FROM user_roles"))
    if settings.admin_email:
        op.execute(
            sa.text("DELETE FROM users WHERE email = :email").bindparams(email=settings.admin_email.lower())
        )
    op.execute(sa.text("DELETE FROM role_permissions"))
    op.execute(sa.text("DELETE FROM roles"))
    op.execute(sa.text("DELETE FROM permissions"))
    op.execute(
        sa.text("DELETE FROM organizations WHERE slug = :slug").bindparams(
            slug=settings.default_organization_slug
        )
    )
