"""add risk events and risk score snapshots

Revision ID: 3df528190e3f
Revises: 38039e033cd7
Create Date: 2026-07-22 00:36:41.812149
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '3df528190e3f'
down_revision: str | None = '38039e033cd7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('camera_id', sa.String(length=100), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=True),
    sa.Column('hazard_class', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('severity', sa.Float(), nullable=False),
    sa.Column('bbox_x1', sa.Float(), nullable=True),
    sa.Column('bbox_y1', sa.Float(), nullable=True),
    sa.Column('bbox_x2', sa.Float(), nullable=True),
    sa.Column('bbox_y2', sa.Float(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_risk_events_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_risk_events_zone_id_zones'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_events'))
    )
    op.create_index(op.f('ix_risk_events_detected_at'), 'risk_events', ['detected_at'], unique=False)
    op.create_index(op.f('ix_risk_events_hazard_class'), 'risk_events', ['hazard_class'], unique=False)
    op.create_index(op.f('ix_risk_events_organization_id'), 'risk_events', ['organization_id'], unique=False)
    op.create_index('ix_risk_events_zone_detected_at', 'risk_events', ['zone_id', 'detected_at'], unique=False)
    op.create_index(op.f('ix_risk_events_zone_id'), 'risk_events', ['zone_id'], unique=False)
    op.create_table('risk_score_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_score', sa.Float(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risklevel', native_enum=False, length=20), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risklevel', native_enum=False, length=20), nullable=False),
    sa.Column('dominant_hazard_class', sa.String(length=50), nullable=True),
    sa.Column('predicted_score', sa.Float(), nullable=True),
    sa.Column('trend', sa.Enum('INCREASING', 'STABLE', 'DECREASING', name='trend', native_enum=False, length=20), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('contributing_event_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_risk_score_snapshots_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_risk_score_snapshots_zone_id_zones'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_score_snapshots'))
    )
    op.create_index(op.f('ix_risk_score_snapshots_computed_at'), 'risk_score_snapshots', ['computed_at'], unique=False)
    op.create_index(op.f('ix_risk_score_snapshots_organization_id'), 'risk_score_snapshots', ['organization_id'], unique=False)
    op.create_index('ix_risk_score_snapshots_zone_computed_at', 'risk_score_snapshots', ['zone_id', 'computed_at'], unique=False)
    op.create_index(op.f('ix_risk_score_snapshots_zone_id'), 'risk_score_snapshots', ['zone_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_score_snapshots_zone_id'), table_name='risk_score_snapshots')
    op.drop_index('ix_risk_score_snapshots_zone_computed_at', table_name='risk_score_snapshots')
    op.drop_index(op.f('ix_risk_score_snapshots_organization_id'), table_name='risk_score_snapshots')
    op.drop_index(op.f('ix_risk_score_snapshots_computed_at'), table_name='risk_score_snapshots')
    op.drop_table('risk_score_snapshots')
    op.drop_index(op.f('ix_risk_events_zone_id'), table_name='risk_events')
    op.drop_index('ix_risk_events_zone_detected_at', table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_organization_id'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_hazard_class'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_detected_at'), table_name='risk_events')
    op.drop_table('risk_events')
    # ### end Alembic commands ###
